# 
#   Copyright (C) 2018 CASM Organization <https://casm-lang.org>
#   All rights reserved.
# 
#   Developed by: Philipp Paulweber
#                 <https://github.com/casm-lang/casm-lang.container.windows>
# 
#   This file is part of casm-lang.container.windows.
# 
#   casm-lang.container.windows is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
# 
#   casm-lang.container.windows is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License
#   along with casm-lang.container.windows. If not, see <http://www.gnu.org/licenses/>.
# 

* Windows Docker Container C++ Build Environment

Provides a =Dockerfile= which creates a C++ build environment for Windows.

** Status [[https://cirrus-ci.com/github/casm-lang/casm-lang.container.windows][https://api.cirrus-ci.com/github/casm-lang/casm-lang.container.windows.svg]]

TBD


** Copyright and License

The copyright holder of 
=casm-lang.container.windows= is the [[https://casm-lang.org][CASM organization]] ([[https://github.com/casm-lang][@casm-lang]])
and the used license of 
=casm-lang.container.windows= is the [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3]].

*** Notice

#+begin_src

Copyright (C) 2018 CASM Organization <https://casm-lang.org>
All rights reserved.

Developed by: Philipp Paulweber
              <https://github.com/casm-lang/casm-lang.container.windows>

This file is part of casm-lang.container.windows.

casm-lang.container.windows is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

casm-lang.container.windows is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with casm-lang.container.windows. If not, see <http://www.gnu.org/licenses/>.

#+end_src
